---
include:
  - project: elise/shared-cicd
    ref: main
    file: .gitlab-ci.yml

  - local: ci/ssl_renew.yml
    rules:
      - if: |
          $CI_COMMIT_BRANCH == "main" &&
          $ELISE_SCHEDULE_SSL_RENEW &&
          $CI_PIPELINE_SOURCE == "schedule"
