---
variables:
  ELISE_PIPELINE_MODULE_NAME:
    description: name of folder in 'terraform/modules'

  ELISE_PIPELINE_VAR_FILE_NAME:
    description: name of folder and file in 'terraform/elysianskies'

include:
  - project: elise/shared-cicd
    ref: main
    file: .gitlab-ci.yml
