---
services:

  ###########################################################
  # init
  ###########################################################

  init:
    image: docker-hosted.pendragonlab.com/elise/iac-deploy:main
    entrypoint: |
      terraform -chdir=/terraform/environment init
    profiles:
      - init

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raid_vol
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

  ###########################################################
  # validate
  ###########################################################

  validate:
    image: docker-hosted.pendragonlab.com/elise/iac-deploy:main
    entrypoint: |
      terraform -chdir=/terraform/environment validate
    profiles:
      - validate

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raid_vol
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

  ###########################################################
  # plan
  ###########################################################

  plan:
    image: docker-hosted.pendragonlab.com/elise/iac-deploy:main
    entrypoint: |
      terraform -chdir=/terraform/environment plan
    profiles:
      - plan

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raid_vol
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

  ###########################################################
  # apply
  ###########################################################

  apply:
    image: docker-hosted.pendragonlab.com/elise/iac-deploy:main
    entrypoint: |
      terraform -chdir=/terraform/environment apply -auto-approve
    profiles:
      - apply

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raid_vol
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

  ###########################################################
  # destroy
  ###########################################################

  destroy:
    image: docker-hosted.pendragonlab.com/elise/iac-deploy:main
    entrypoint: |
      terraform
        -chdir=/terraform/environment destroy
        -target module.domain_lab
        -target module.firewall_lab
        -target module.instance_portal
        -target module.vpc_lab
        -auto-approve
    profiles:
      - destroy

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raid_vol
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

  destroy_all:
    image: docker-hosted.pendragonlab.com/elise/iac-deploy:main
    entrypoint: |
      terraform
        -chdir=/terraform/environment destroy
        -auto-approve
    profiles:
      - destroy-all

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raid_vol
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

  ###########################################################
  # output
  ###########################################################

  output:
    image: docker-hosted.pendragonlab.com/elise/iac-deploy:main
    entrypoint: |
      terraform -chdir=/terraform/environment output
    profiles:
      - output

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raid_vol
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

###########################################################
# resources
###########################################################

volumes:
  raid_vol:
    driver_opts:
      type: cifs
      o: username=${RAID_VOL_USERNAME},password=${RAID_VOL_PASSWORD},uid=${LOCAL_USER_UID},gid=${LOCAL_USER_UID},iocharset=utf8
      device: //${RAID_VOL_HOST}/${RAID_VOL_SHARE}

networks:
  iac_deploy:
    name: iac_deploy
