---
services:

  ###########################################################
  # init
  ###########################################################

  init:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-deploy:main
    entrypoint: terraform -chdir=/terraform/environment init

    profiles:
      - init

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raidvol_green_share
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ###########################################################
  # validate
  ###########################################################

  validate:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-deploy:main
    entrypoint: terraform -chdir=/terraform/environment validate

    profiles:
      - validate

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raidvol_green_share
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ###########################################################
  # plan
  ###########################################################

  plan:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-deploy:main
    entrypoint: terraform -chdir=/terraform/environment plan

    profiles:
      - plan

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raidvol_green_share
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ###########################################################
  # apply
  ###########################################################

  apply:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-deploy:main
    entrypoint: terraform -chdir=/terraform/environment apply -auto-approve

    profiles:
      - apply

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raidvol_green_share
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

    logging:
      options:
        max-size: 10m
        max-file: '10'

  ###########################################################
  # destroy
  ###########################################################

  destroy:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-deploy:main
    entrypoint: |
      terraform
        -chdir=/terraform/environment destroy
        -target=module.instance_portal
        -target=module.firewall_lab
        -auto-approve

    profiles:
      - destroy

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raidvol_green_share
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

    logging:
      options:
        max-size: 10m
        max-file: '10'

  destroy_all:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-deploy:main
    entrypoint: |
      terraform
        -chdir=/terraform/environment destroy
        -auto-approve

    profiles:
      - destroy-all

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: bind
        source: terraform/environment
        target: /terraform/environment
        read_only: false

      - type: volume
        source: raidvol_green_share
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

    logging:
      options:
        max-size: 10m
        max-file: '10'

###########################################################
# resources
###########################################################

volumes:
  raidvol_green_share:
    driver_opts:
      type: cifs
      o: "\
        username=${RAIDVOL_GREEN_SHARE_USERNAME},\
        password=${RAIDVOL_GREEN_SHARE_PASSWORD},\
        uid=${RAIDVOL_GREEN_SHARE_UID},\
        gid=${RAIDVOL_GREEN_SHARE_GID},\
        dir_mode=0770,\
        file_mode=0770,\
        iocharset=utf8"
      device: //${RAIDVOL_GREEN_SHARE_HOST}/${RAIDVOL_GREEN_SHARE_NAME}

networks:
  iac_deploy:
    name: iac_deploy
