---
services:

  ###########################################################
  # run
  ###########################################################

  run:
    image: docker-hosted.proxy-int.pendragonlab.com/elise/iac-deploy:main
    entrypoint: terraform -chdir=/terraform/environment ${TERRAFORM_ARGS}

    environment:
      - TZ=America/Denver

    volumes:
      - type: bind
        source: ${USER_APPROLE_FOLDER}
        target: /approle
        read_only: true

      - type: bind
        source: ${USER_AUTOMATION_FOLDER}
        target: /automation
        read_only: true

      - type: bind
        source: terraform
        target: /terraform
        read_only: false

      - type: volume
        source: raidvol_green_share
        target: /tfstate
        read_only: false

    networks:
      - iac_deploy

    logging:
      options:
        max-size: 10m
        max-file: '10'

###########################################################
# resources
###########################################################

volumes:
  raidvol_green_share:
    driver_opts:
      type: cifs
      o: "\
        username=${RAIDVOL_GREEN_SHARE_USERNAME},\
        password=${RAIDVOL_GREEN_SHARE_PASSWORD},\
        uid=${RAIDVOL_GREEN_SHARE_UID},\
        gid=${RAIDVOL_GREEN_SHARE_GID},\
        dir_mode=0770,\
        file_mode=0770,\
        iocharset=utf8"
      device: //${RAIDVOL_GREEN_SHARE_HOST}/${RAIDVOL_GREEN_SHARE_NAME}

networks:
  iac_deploy:
    name: iac_deploy
