---
services:

  ###########################################################
  # builder
  ###########################################################

  builder:
    build:
      context: .
      tags:
        - docker01-teine.home.elysianskies.com:32501/elise/iac-deploy:main
    profiles:
      - builder

  ###########################################################
  # terragrunt_plan
  ###########################################################

  terragrunt_plan:
    image: docker01-teine.home.elysianskies.com:32501/elise/iac-deploy:main
    entrypoint: |
      terragrunt run-all
          plan
    profiles:
      - plan

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: volume
        source: tvault
        target: /tfstate
        read_only: false
        volume: 
          subpath: elysianskies/tfstate

    networks:
      - iac_deploy

  ###########################################################
  # terragrunt_apply
  ###########################################################

  terragrunt_apply:
    image: docker01-teine.home.elysianskies.com:32501/elise/iac-deploy:main
    entrypoint: |
      terragrunt run-all
          apply
          --terragrunt-non-interactive
    profiles:
      - apply

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}

    volumes:
      - type: volume
        source: tvault
        target: /tfstate
        read_only: false
        volume: 
          subpath: elysianskies/tfstate

    networks:
      - iac_deploy

  ###########################################################
  # terragrunt_destroy
  ###########################################################

  terragrunt_destroy:
    image: docker01-teine.home.elysianskies.com:32501/elise/iac-deploy:main
    entrypoint: |
      terragrunt run-all
          destroy
          --terragrunt-non-interactive
    profiles:
      - destroy

    environment:
      - TZ=America/Denver
      - LINODE_TOKEN=${LINODE_TOKEN}
      - TERRAGRUNT_EXCLUDE_DIR=/terraform/inputs/nginx_certificate

    volumes:
      - type: volume
        source: tvault
        target: /tfstate
        read_only: false
        volume: 
          subpath: elysianskies/tfstate

    networks:
      - iac_deploy

###########################################################
# resources
###########################################################

volumes:
  tvault:
    driver_opts:
      type: cifs
      o: username=${TVAULT_USERNAME},password=${TVAULT_PASSWORD},uid=1000,gid=1000,iocharset=utf8
      device: //172.16.16.4/tvault

networks:
  iac_deploy:
    name: iac_deploy
