---
build_docker_terraform:
  stage: integrate
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      changes:
        - terraform/*
        - terraform/*/*
        - terraform/*/*/*
        - Dockerfile
  script:
    - |
      DOCKER_BUILDKIT=1 docker build . \
          --tag "$ELISE_CI_NEXUS_HOSTED/elise/elysianskies-linode:$CI_COMMIT_REF_SLUG"
    - docker push "$ELISE_CI_NEXUS_HOSTED/elise/elysianskies-linode:$CI_COMMIT_REF_SLUG"
